version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
       - data-psql:/data/postgres
    ports:
      - "5500:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - ///c/Users/verie/OneDrive/เดสก์ท็อป/ionic-try-2/pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
  
  node-api:
    container_name: node-api
    build: ./server/.
    image: node:13.8.0-alpine3.11
    volumes:
        - "./server:/server"
    ports:
      - "${NODE_PORT:-3000}:3000"
    networks:
      - postgres
    restart: unless-stopped

volumes:
  data-psql:
    driver: local


networks:
  postgres:
    driver: bridge
