version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
       - data-psql:/data/postgres
    ports:
      - "5500:5432"
    networks:
      - internal
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pg-admin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - internal
    restart: unless-stopped
  
  node-api:
    container_name: node-api
    build: ./server/.
    image: node:13.8.0-alpine3.11
    volumes:
        - "./server:/server"
    ports:
      - "${NODE_PORT:-3000}:3000"
    networks:
      - internal
    restart: unless-stopped

  python-http-server:
    container_name: python-http-server
    build: ./picture/.
    image: python:3.9.0a5-alpine3.11
    ports:
      - "51412:51412"
    networks:
      - internal
    restart: unless-stopped

volumes:
  data-psql:
    driver: local
  pg-admin:
    driver: local
  

networks:
  internal:
    driver: bridge
